server {
    listen 80;
    root /app;
    index index.html;

    location / {
        rewrite ^/pages/([a-zA-Z-]+)\.(php|html)$ /$1 permanent;
        rewrite ^/([a-zA-Z-]+)\.(php|html)$ /$1 permanent;
        try_files $uri $uri.html $uri/ @pages;
    }

    location @pages {
        rewrite ^/([a-zA-Z-]+)/?$ /pages/$1.html last;
        return 404;
    }
}
